apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-production-secret
type: generic
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: gasper@aerio.tech
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik