apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: observability-sa
    namespace: observability
roleRef:
  kind: ClusterRole
  name: observability-pod-reader
  apiGroup: rbac.authorization.k8s.io