apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]