apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.name" . }}
  labels:
    {{ include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "todo-app.name" . }}
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP