{{- if .Values.app.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "todo-app.name" . }}
  labels:
    {{ include "todo-app.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.app.gateway.name }}
      namespace: {{ .Values.app.gateway.namespace }}
  hostnames:
    {{- range .Values.app.gateway.hosts }}
    - {{ . }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "todo-app.name" . }}
          port: 8080
{{- end }}